---
abstract: 'Hexadecimal Range Dumper with color, bitfields and skip ranges'
author:
  - 'Nadim ibn hamouda el Khemir. <nkh@cpan.org>'
build_requires:
  Test::Block: 0
  Test::Exception: 0
  Test::NoWarnings: 0
  Test::Warn: 0
  Text::Diff: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-HexDump-Range
provides:
  Data::HexDump::Range:
    file: lib/Data/HexDump/Range.pm
    version: 0.12
requires:
  Data::TreeDumper: 0
  Getopt::Long: 0
  List::MoreUtils: 0
  List::Util: 0
  Readonly: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  Term::Bash::Completion::Generator: 0
  Text::Colorizer: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.12.57
